### ISSUE TITLE
JSONParser not found

### ISSUE THREAD

**Issue by ghost** [ShengHuaWu/SimpleApiClient#1]
The JSONParser is nowhere to be found and the link provided is not working anymore

**Comment by ShengHuaWu** [comment]
@smidaharoun 
Thank you for mentioning that.
I used my own JSONParser component in this project, but that is removed. 
Therefore, please choose [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON) for Swift 3, or _Codable_ protocol for Swift 4.

**Comment by ghost** [comment]
Thanks @ShengHuaWu
